### ISSUE TITLE
Logging out sets next to /logout after redirecting to the login page

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyclops#1]
When you logout through the frontend, you get redirected to /login?next=%2Flogout

So you when you try to login again you immediately get redirected/logged out. Logging out should set the next parameters to /app or something else

**Comment by chasepbrewer** [comment]
I also recently discovered this bug during development. The application has /app as the default reroute, but if someone was rerouted from the logout page the next parameter gets set to /logout instead. This means that whenever someone logs out, they can get stuck in an infinite logout loop.

I'm fixing this in the next patch, but for the time being if you find yourself in this trap just type in '/' or '/login' on the URL path, hit enter, and it should reset itself so that it redirects to /app. Sorry about the inconvenience.
